/**
 * ReportHistoryViewer Component
 * 
 * Displays history of all report generations (manual and scheduled).
 * Allows filtering, searching, and viewing past report results.
 * 
 * Features:
 * - View all report executions
 * - Filter by status, type, template
 * - Search by template name
 * - View execution details
 * - Re-run from history
 * - Export history to CSV
 * 
 * Design System V4.1 Compliant
 */

import React, { useState, useMemo } from 'react';
import { User } from '../../../../types';
import { ReportHistoryEntry } from '../../../../types/report-history';
import { 
  getReportHistory, 
  getHistoryStatistics,
  clearAllHistory 
} from '../../../../lib/report-history';
import { WorkspaceHeader } from '../../../workspace/WorkspaceHeader';
import { Button } from '../../../ui/button';
import { Input } from '../../../ui/input';
import { 
  History,
  Clock,
  CheckCircle,
  XCircle,
  Play,
  Search,
  Download,
  Trash2,
  Filter,
  Calendar,
  User as UserIcon,
  FileText,
  TrendingUp,
  Zap
} from 'lucide-react';
import { toast } from 'sonner';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../../../ui/table';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from '../../../ui/dropdown-menu';
import { Badge } from '../../../ui/badge';
import { CustomReportTemplate } from '../../../../types/custom-reports';

interface ReportHistoryViewerProps {
  user: User;
  templates: CustomReportTemplate[];
  onRunTemplate: (template: CustomReportTemplate) => void;
  onClose: () => void;
}

type StatusFilter = 'all' | 'success' | 'failed';
type TypeFilter = 'all' | 'manual' | 'scheduled';

export const ReportHistoryViewer: React.FC<ReportHistoryViewerProps> = ({
  user,
  templates,
  onRunTemplate,
  onClose,
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('all');
  const [typeFilter, setTypeFilter] = useState<TypeFilter>('all');
  const [selectedEntry, setSelectedEntry] = useState<ReportHistoryEntry | null>(null);

  // Load history
  const history = useMemo(() => getReportHistory(), []);
  const stats = useMemo(() => getHistoryStatistics(), []);

  // Filter history
  const filteredHistory = useMemo(() => {
    return history.filter(entry => {
      // Search filter
      if (searchQuery && !entry.templateName.toLowerCase().includes(searchQuery.toLowerCase())) {
        return false;
      }

      // Status filter
      if (statusFilter !== 'all' && entry.status !== statusFilter) {
        return false;
      }

      // Type filter
      if (typeFilter !== 'all' && entry.executionType !== typeFilter) {
        return false;
      }

      return true;
    });
  }, [history, searchQuery, statusFilter, typeFilter]);

  // Format date
  const formatDate = (dateString: string): string => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  // Format execution time
  const formatExecutionTime = (ms?: number): string => {
    if (!ms) return 'N/A';
    if (ms < 1000) return `${Math.round(ms)}ms`;
    return `${(ms / 1000).toFixed(2)}s`;
  };

  // Handle re-run
  const handleReRun = (entry: ReportHistoryEntry) => {
    const template = templates.find(t => t.id === entry.templateId);
    if (!template) {
      toast.error('Template not found');
      return;
    }
    onRunTemplate(template);
  };

  // Handle clear history
  const handleClearHistory = () => {
    if (!confirm('Are you sure you want to clear all report history? This cannot be undone.')) {
      return;
    }

    try {
      clearAllHistory();
      toast.success('Report history cleared');
      onClose();
    } catch (error) {
      toast.error('Failed to clear history');
    }
  };

  // Export history to CSV
  const handleExportHistory = () => {
    const csvRows = [
      ['Generated At', 'Template', 'Type', 'Status', 'Rows', 'Execution Time', 'Generated By'].join(','),
      ...filteredHistory.map(entry => 
        [
          new Date(entry.generatedAt).toISOString(),
          `"${entry.templateName}"`,
          entry.executionType,
          entry.status,
          entry.rowCount || 0,
          entry.executionTimeMs || 0,
          entry.generatedBy,
        ].join(',')
      ),
    ];

    const csvContent = csvRows.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `report-history-${new Date().toISOString()}.csv`;
    a.click();
    URL.revokeObjectURL(url);

    toast.success('History exported to CSV');
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <WorkspaceHeader
        title="Report History"
        description="View and manage report generation history"
        stats={[
          {
            label: 'Total Runs',
            value: stats.totalReports,
            variant: 'default',
          },
          {
            label: 'Successful',
            value: stats.successfulRuns,
            variant: 'success',
          },
          {
            label: 'Failed',
            value: stats.failedRuns,
            variant: 'danger',
          },
          {
            label: 'Avg Time',
            value: formatExecutionTime(stats.averageExecutionTime),
            variant: 'info',
          },
        ]}
        secondaryActions={[
          {
            label: 'Export History',
            icon: <Download className="h-4 w-4" />,
            onClick: handleExportHistory,
            disabled: filteredHistory.length === 0,
          },
          {
            label: 'Clear All',
            icon: <Trash2 className="h-4 w-4" />,
            onClick: handleClearHistory,
            variant: 'destructive',
            disabled: history.length === 0,
          },
        ]}
      />

      {/* Filters Bar */}
      <div className="bg-white border-b border-gray-300 px-6 py-4">
        <div className="flex items-center gap-4">
          {/* Search */}
          <div className="flex-1 relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-500" />
            <Input
              placeholder="Search templates..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10"
            />
          </div>

          {/* Status Filter */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="sm">
                <Filter className="h-4 w-4 mr-2" />
                Status: {statusFilter === 'all' ? 'All' : statusFilter}
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={() => setStatusFilter('all')}>
                All Statuses
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => setStatusFilter('success')}>
                <CheckCircle className="h-4 w-4 mr-2 text-green-600" />
                Successful
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => setStatusFilter('failed')}>
                <XCircle className="h-4 w-4 mr-2 text-red-600" />
                Failed
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          {/* Type Filter */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="sm">
                <Zap className="h-4 w-4 mr-2" />
                Type: {typeFilter === 'all' ? 'All' : typeFilter}
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={() => setTypeFilter('all')}>
                All Types
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => setTypeFilter('manual')}>
                <UserIcon className="h-4 w-4 mr-2" />
                Manual
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => setTypeFilter('scheduled')}>
                <Calendar className="h-4 w-4 mr-2" />
                Scheduled
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        {/* Active Filters */}
        {(searchQuery || statusFilter !== 'all' || typeFilter !== 'all') && (
          <div className="flex items-center gap-2 mt-3">
            <span className="text-sm text-gray-600">Active filters:</span>
            {searchQuery && (
              <Badge variant="secondary" className="gap-1">
                Search: {searchQuery}
                <button
                  onClick={() => setSearchQuery('')}
                  className="ml-1 hover:bg-gray-300 rounded-full p-0.5"
                >
                  ×
                </button>
              </Badge>
            )}
            {statusFilter !== 'all' && (
              <Badge variant="secondary" className="gap-1">
                Status: {statusFilter}
                <button
                  onClick={() => setStatusFilter('all')}
                  className="ml-1 hover:bg-gray-300 rounded-full p-0.5"
                >
                  ×
                </button>
              </Badge>
            )}
            {typeFilter !== 'all' && (
              <Badge variant="secondary" className="gap-1">
                Type: {typeFilter}
                <button
                  onClick={() => setTypeFilter('all')}
                  className="ml-1 hover:bg-gray-300 rounded-full p-0.5"
                >
                  ×
                </button>
              </Badge>
            )}
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                setSearchQuery('');
                setStatusFilter('all');
                setTypeFilter('all');
              }}
              className="text-xs"
            >
              Clear all
            </Button>
          </div>
        )}
      </div>

      {/* History Table */}
      <div className="p-6">
        {filteredHistory.length === 0 ? (
          <div className="bg-white border border-gray-300 rounded-lg p-12 text-center">
            <History className="h-12 w-12 text-gray-400 mx-auto mb-4" />
            <h3 className="text-gray-900 mb-2">No Report History</h3>
            <p className="text-gray-600">
              {history.length === 0
                ? 'Report history will appear here once you run reports.'
                : 'No reports match your filters. Try adjusting the filters above.'
              }
            </p>
          </div>
        ) : (
          <div className="bg-white border border-gray-300 rounded-lg overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Template</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Rows</TableHead>
                  <TableHead>Execution Time</TableHead>
                  <TableHead>Generated</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredHistory.map(entry => (
                  <TableRow key={entry.id}>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <FileText className="h-4 w-4 text-gray-500" />
                        <span>{entry.templateName}</span>
                      </div>
                    </TableCell>
                    <TableCell>
                      <Badge variant={entry.executionType === 'scheduled' ? 'default' : 'secondary'}>
                        {entry.executionType === 'scheduled' ? (
                          <>
                            <Calendar className="h-3 w-3 mr-1" />
                            Scheduled
                          </>
                        ) : (
                          <>
                            <UserIcon className="h-3 w-3 mr-1" />
                            Manual
                          </>
                        )}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      {entry.status === 'success' ? (
                        <Badge variant="success">
                          <CheckCircle className="h-3 w-3 mr-1" />
                          Success
                        </Badge>
                      ) : entry.status === 'failed' ? (
                        <Badge variant="destructive">
                          <XCircle className="h-3 w-3 mr-1" />
                          Failed
                        </Badge>
                      ) : (
                        <Badge variant="secondary">
                          <Clock className="h-3 w-3 mr-1" />
                          Running
                        </Badge>
                      )}
                    </TableCell>
                    <TableCell>
                      {entry.rowCount !== undefined ? (
                        <span className="text-gray-900">{entry.rowCount.toLocaleString()}</span>
                      ) : (
                        <span className="text-gray-500">—</span>
                      )}
                    </TableCell>
                    <TableCell>
                      <span className="text-gray-900">
                        {formatExecutionTime(entry.executionTimeMs)}
                      </span>
                    </TableCell>
                    <TableCell>
                      <div className="text-sm">
                        <div className="text-gray-900">{formatDate(entry.generatedAt)}</div>
                      </div>
                    </TableCell>
                    <TableCell className="text-right">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleReRun(entry)}
                        disabled={!templates.find(t => t.id === entry.templateId)}
                      >
                        <Play className="h-4 w-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        )}
      </div>

      {/* Results Summary */}
      <div className="px-6 pb-6">
        <div className="text-sm text-gray-600">
          Showing {filteredHistory.length} of {history.length} report run{history.length !== 1 ? 's' : ''}
        </div>
      </div>
    </div>
  );
};
